export function fname2mime(name) {
    const MIME_MAP = {
        "3gp":"video/3gp", "7z":"application/x-7z-compressed", "asp":"application/x-aspx",
        "aspx":"application/x-aspx", "bmp":"image/bmp", "bson":"application/bson",
        "bz":"application/x-bzip2", "bz2":"application/x-bzip2", "c":"text/x-c",
        "c++":"text/x-c++src", "cbl":"text/x-cobol", "cc":"text/x-c++src",
        "cgi":"application/x-httpd-cgi", "cob":"text/x-cobol", "coffee":"text/x-coffeescript",
        "cpp":"text/x-c++src", "cs":"text/x-csharp", "csrc":"text/x-csrc",
        "css":"text/css", "csv":"text/csv", "cur":"image/vnd.microsoft.icon",
        "doc":"application/msword", "docm":"application/vnd.ms-word.document.macroEnabled.12",
        "docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "dot":"application/msword", "dotm":"application/vnd.ms-word.template.macroEnabled.12",
        "dotx":"application/vnd.openxmlformats-officedocument.wordprocessingml.template",
        "dtd":"application/xml-dtd", "dxf":"application/dxf", "ejs":"application/x-ejs",
        "emf":"application/emf", "erb":"application/x-erb", "es":"text/ecmascript",
        "f":"text/x-fortran", "f90":"text/x-fortran", "f95":"text/x-fortran",
        "frag":"x-shader/x-fragment", "gif":"image/gif", "gz":"application/x-gzip",
        "h":"text/x-chdr", "h++":"text/x-c++hdr", "hpp":"text/x-c++hdr",
        "hql":"text/x-hive", "html":"text/html", "ico":"image/vnd.microsoft.icon",
        "j2c":"image/jp2", "j2k":"image/jp2", "jar":"application/java-archive",
        "java":"text/x-java", "jp2":"image/jp2", "jpeg":"image/jpeg",
        "jpf":"image/jp2", "jpg":"image/jpeg", "jpm":"image/jp2",
        "jpx":"image/jp2", "js":"text/javascript", "json":"application/json",
        "jsp":"application/x-jsp", "kml":"application/vnd.google-earth.kml+xml",
        "kmz":"application/vnd.google-earth.kmz", "less":"text/x-less",
        "lza":"application/x-lzh-compressed", "lzh":"application/x-lzh-compressed",
        "m":"text/x-objectivec", "m4p":"audio/x-m4p", "markdown":"text/x-markdown",
        "md":"text/x-markdown", "mid":"audio/midi", "midi":"audio/midi",
        "mj2":"image/jp2", "mov":"video/quicktime", "mp3":"audio/mp3",
        "mp4":"video/mp4", "msv":"video/x-msvideo", "nesc":"text/x-nesc",
        "odb":"application/vnd.oasis.opendocument.database", "odc":"application/vnd.oasis.opendocument.chart",
        "odf":"application/vnd.oasis.opendocument.formula", "odg":"application/vnd.oasis.opendocument.graphics",
        "odh":"application/vnd.oasis.opendocument.text-web", "odi":"application/vnd.oasis.opendocument.image",
        "odm":"application/vnd.oasis.opendocument.text-master", "odp":"application/vnd.oasis.opendocument.presentation",
        "ods":"application/vnd.oasis.opendocument.spreadsheet", "odt":"application/vnd.oasis.opendocument.text",
        "oga":"audio/ogg", "ogg":"video/ogg", "ogv":"video/ogg",
        "otg":"application/vnd.oasis.opendocument.graphics-template", "otp":"application/vnd.oasis.opendocument.presentation-template",
        "ots":"application/vnd.oasis.opendocument.spreadsheet-template", "ott":"application/vnd.oasis.opendocument.text-template",
        "oxt":"application/vnd.openofficeorg.extension", "p":"text/x-pascal",
        "pcx":"image/x-pcx", "pdf":"application/pdf", "perl":"text/x-perl",
        "php":"text/x-php", "pl":"text/x-perl", "png":"image/png",
        "pot":"application/vnd.ms-powerpoint", "potm":"application/vnd.ms-powerpoint.template.macroEnabled.12",
        "potx":"application/vnd.openxmlformats-officedocument.presentationml.template", "ppa":"application/vnd.ms-powerpoint",
        "ppam":"application/vnd.ms-powerpoint.addin.macroEnabled.12", "pps":"application/vnd.ms-powerpoint",
        "ppsm":"application/vnd.ms-powerpoint.slideshow.macroEnabled.12", "ppsx":"application/vnd.openxmlformats-officedocument.presentationml.slideshow",
        "ppt":"application/vnd.ms-powerpoint", "pptm":"application/vnd.ms-powerpoint.presentation.macroEnabled.12",
        "pptx":"application/vnd.openxmlformats-officedocument.presentationml.presentation", "psd":"image/vnd.adobe.photoshop",
        "py":"text/x-python", "pyx":"text/x-cython", "rar":"application/x-rar-compressed",
        "rb":"text/x-ruby", "rpm":"audio/x-pn-realaudio-plugin", "rtf":"application/rtf",
        "ruby":"text/x-ruby", "scala":"text/x-scala", "scss":"text/x-scss",
        "sh":"text/x-sh", "sql":"text/x-sql", "sv":"text/x-systemverilog",
        "svg":"image/svg+xml", "svgz":"image/svg+xml", "swf":"application/x-shockwave-flash",
        "tar":"application/x-tar", "tbz":"application/x-bzip2", "text":"text/plain",
        "tgz":"application/x-gzip", "tif":"image/tiff", "tiff":"image/tiff",
        "tlv":"text/x-tlv", "ts":"text/typescript", "tsv":"text/tab-separated-values",
        "txt":"text/plain", "v":"text/x-verilog", "vb":"text/x-vb",
        "vbs":"text/vbscript", "vert":"x-shader/x-vertex", "vhd":"text/x-vhdl",
        "wav":"audio/wav", "webm":"video/webm", "webp":"image/webp",
        "wmv":"video/x-ms-wmv", "xcf":"image/xcf", "xhtml":"application/xhtml+xml",
        "xla":"application/vnd.ms-excel", "xlam":"application/vnd.ms-excel.addin.macroEnabled.12",
        "xls":"application/vnd.ms-excel", "xlsb":"application/vnd.ms-excel.sheet.binary.macroEnabled.12",
        "xlsm":"application/vnd.ms-excel.sheet.macroEnabled.12", "xlsx":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xlt":"application/vnd.ms-excel", "xltm":"application/vnd.ms-excel.template.macroEnabled.12",
        "xltx":"application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xml":"text/xml",
        "xslt":"application/xslt+xml", "xz":"application/x-xz", "zip":"application/x-zip-compressed",
        "pages":"application/vnd.apple.pages", "numbers":"application/vnd.apple.numbers", "key":"application/vnd.apple.keynote",
        "shp":"application/octet-stream", "dbf":"application/x-dbf", "shx":"application/octet-stream",
        "geojson":"application/geo+json", "topojson":"application/json", "gpx":"application/gpx+xml",
        "altpbf": "application/x-altpbf",
        "geopbf": "application/x-geopbf",
    };
    return MIME_MAP[name.split(".").reverse()[0].toLowerCase()] || "application/octet-stream";
}
