name: Deploy Demo
on:
  push:
    branches: ["main"] # メインブランチにプッシュした時に実行
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install # package.jsonに基づき依存関係をインストール
      - run: npm run build # vite buildを実行してdistを作成
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - uses: actions/deploy-pages@v4